config/routes.rb
Ribbitapp::Application.routes.draw do
  resources :relationships


  resources :ribbits


  resources :sessions
  resources :users

  get 'logout', to: 'sessions#destroy', as: 'logout'


  root to: "users#new"



  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/models/relationship.rb
class Relationship < ActiveRecord::Base
  attr_accessible :followed_id, :follower_id
  belongs_to :follower, class_name: 'User'
  belongs_to :followed, class_name: 'User'
end

app/models/ribbit.rb
class Ribbit < ActiveRecord::Base
  attr_accessible :content, :user_id
  default_scope order: "created_at DESC"  #returned with the newest ribbit

  belongs_to :user

  validate :content, length: {maximum: 140}

end

app/models/user.rb
require 'digest/md5'

class User < ActiveRecord::Base
  attr_accessible :avatar_url, :bio, :email, :name, :password, :password_confirmation, :username
  has_secure_password

  #relationships
  has_many :ribbits

  has_many :follower_relationships, class_name: 'Relationship', foreign_key: 'followed_id'
  has_many :followed_relationships, class_name: 'Relationship', foreign_key: 'follower_id'
  has_many :followers, through: :follower_relationships
  has_many :followeds, through: :followed_relationships

  before_validation :prep_email
  before_save :create_avatar_url

  validates :email, presence: true,
                    uniqueness: true,
                    format: {with: /^[\w\.+-]+@([\w]+\.)+[a-zA-Z]+$/}
  validates :username, presence: :true, uniqueness: true
  validates :name, presence: :true


  def following? user
    self.followeds.include? user
  end

  def follow user
    Relationship.create follower_id self.id, followed_id: user.id
  end

  private

  def prep_email
    self.email = self.email.strip.downcase if self.email
  end

  def create_avatar_url
    self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  private

  def current_user
    if session[:user_id]
      @current_user ||=User.find(session[:user_id])
    end
  end

  helper_method :current_user

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    relationship = Relationship.new(params[:relationship])
    relationship.follower = current_user

    if relationship.save
      redirect_to relationship.followed
    else
      flash[:error] = "Opps.  You cannot follow."
      redirect_to relationship.followed
    end
  end

    def destroy
      relationship = Relationship.find(params[:id])
      user = relationship.followed
      relationship.destroy
      redirect_to user
    end
end

app/controllers/ribbits_controller.rb
class RibbitsController < ApplicationController
  def index
    @ribbits = Ribbit.all
    @ribbit = Ribbit.new
  end
  def create
    ribbit = Ribbit.new(params[:ribbit])
    ribbit.user_id = current_user.id
    flash[:error] = "Your ribbit was too long." unless ribbit.save
    redirect_to root_url
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.find_by_username params[:username]
    if user and user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "You are logged in."
    else
      flash[:error] = "Wrong username or password"
      redirect_to root_url
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user, notice: "You are signed up!"
    else
      render 'new'
    end
  end

  def index
    @users = User.all
    @ribbit = Ribbit.new
  end

  def show
    @user = User.find(params[:id])
    @ribbit = Ribbit.new
    @relationship = Relationship.where(
      follower_id: current_user.id,
      followed_id: @user.id).first_or_initialize if current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/ribbits_helper.rb
module RibbitsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ribbit</title>
  <link rel="stylesheet/less" href="/style.less" />
  <script src="/less.js"></script>
</head>
<body>
  <header>
    <div class="wrapper">
      <img src= "/gfx/logo.png"/>
      <span> Twitter Clone </span>
      <% if current_user%>
        <%= link_to "Public Ribbits", ribbits_path %>
        <%= link_to "Public Profile", users_path %>
        <%= link_to "My Profile", current_user %>
        <%= link_to "Log Out", logout_path %>
      <% else %>
      <%= form_tag sessions_path do %>
        <%= text_field_tag :username, nil, placeholder: "username" %>
        <%= password_field_tag :password, nil, placeholder: "password" %>
        <%= submit_tag "Log In" %>
        <% end %>
      <% end %>
    </div>
  </header>
<div id="content">
  <div class="wrapper">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, msg, class: "flash #{name}" %>
    <% end %>
    <%= yield %>
  </div>
</div>

<footer>
  <div class="wrapper">
    Ribbit.  A simple Twitter clone <img src="/gfx/logo.nettuts.png">
  </div>
</footer>
</body>
</html>

app/views/ribbits/_new_form.html.erb
<div class="panel right">
  <h1> Create A Ribbit </h1>
  <%= form_for @ribbit do |f| %>
    <%= f.text_area :content, class: "ribbitText", id: "ribbitText" %>
    <%= f.submit "Ribbit!", id: "ribbitBtn" %>
    <span id="charCount">0</span>
  <% end %>
</div>

app/views/ribbits/index.html.erb
<% if current_user %>
  <%= render 'ribbits/new_form' %>
<% end %>

<div class="panel left">
  <h1> Public Ribbits </h1>
  <% @ribbits.each do |ribbit| %>
    <div class="ribbitWrapper">
      <a href = "<%=user_path ribbit.user %>" >
        <img class="avatar" src="<%= ribbit.user.avatar_url %>" />
        <span class="name" <%=ribbit.user.name %> </span>
      </a>
      @<%= ribbit.user.username %>
      <span class="time"><%= time_ago_in_words(ribbit.created_at) %> </span>
      <p> <%= ribbit.content %> </p>
    </div>
  <% end %>
</div>

<%= javascript_include_tag 'ribbits' %>

app/views/users/index.html.erb
<% if current_user %>
  <%= render "ribbits/new_form" %>
<% end %>

<div class="panel left">
  <h1> Public Profiles </h1>
  <% @users.each do |user | %>
      <div class="ribbitWrapper">
        <a href="<%=user_path user%>">
          <img class="avatar" src="<%= user.avatar_url %>" />
          <span class="name"><%= user.name %></span>
        </a>
          @<%= user.username %>
        <p>
          <%= user.ribbits.length %> Ribbits
          <span class="spacing"> <%= user.followers.length %> Followers </span>
          <span class="spacing"> <%= user.followeds.length %> Following </span>
        </p>
        <% if user.bio %>
          <p> <%= user.bio %> </p>
        <% elsif user.ribbits.first %>
          <p> <%=user.ribbits.first.content %> </p>
        <% end %>
      </div>
  <% end %>
</div>

<%= javascript_include_tag "ribbits" %>

app/views/users/new.html.erb
<img src="/gfx/frog.jpg" />
<div class= "panel right">
  <h1> Join Ribbit? </h1>
  <p>
    <%= form_for @user do |f| %>
        <% if @user.errors.any? %>
          <ul>
            <% @user.errors.full_messages.each do |e| %>
              <li> <%= e %> </li>
            <% end %>
          </ul>
         <% end %>
      <%= f.text_field :email, placeholder: "email" %>
      <%= f.text_field :name, placeholder: "name" %>
      <%= f.text_field :username, placeholder: "username" %>
      <%= f.password_field :password, placeholder: "password" %>
      <%= f.password_field :password_confirmation, placeholder: "password" %>
      <%= f.submit "Create Account" %>
    <% end %>

  </p>
</div>

app/views/users/show.html.erb
<% if current_user %>
  <%= render 'ribbits/new_form' %>
<% end %>

<div id="ribbits" class="pannel left">
  <h1> Ribbit Profile </h1>
  <div class="ribbitWrapper">
    <img class="avatar" src="<%= @user.avatar_url %>" />
    <span class="name"><%= @user.name %></span> @<%= @user.username %>
    <p>
      <%= @user.ribbits.length %> Ribbits
      <span class="spacing"> <%= @user.followers.length %> Followers </span>
      <span class="spacing"> <%= @user.followeds.length %> Following </span>

      <% if current_user && @user !=current_user %>
        <% if current_user.following? @user %>
          <%= form_for @relationship, method: :delete do |f| %>
            <%= f.submit "Unfollow" %>
          <% end %>
        <% else %>
          <%= form_for @relationship do |f| %>
            <%= f.hidden_field :followed_id, value: @user.id %>
            <%= f.submit "Follow" %>
          <% end %>
        <% end %>
      <% end %>
    </p>
  </div>
</div>

<div class="panel left">
  <h1> Ribbits </h1>
  <% @user.ribbits.each do |ribbit| %>
    <div class="ribbitWrapper">
        <img class="avatar" src="<%= ribbit.user.avatar_url %>" />
        <span class="name" <%=ribbit.user.name %> </span>
      </a>
      @<%= ribbit.user.username %>
      <span class="time"><%= time_ago_in_words(ribbit.created_at) %> </span>
      <p> <%= ribbit.content %> </p>
    </div>
  <% end %>
</div>

<%= javascript_include_tag 'ribbits' %>